### PR TITLE
AT_04.32.01 | Verify that the "Reset" button is clickable.

### PR DESCRIPTION
**Pull request by MarinaMone**
https://trello.com/c/YW6DjRJr/550-at043201-verify-that-the-reset-button-is-clickable

### CODE REVIEW

**Review by OLgaByR — COMMENTED** [review]
we already have clickResetButton() method in POM

**Comment by MarinaMone** [comment]
> 



> we already have clickResetButton() method in POM

Sorry was not sure in the end but was doubting

**Comment by MarinaMone** [comment]
@OLgaByR should I delete it now and commit again ?

**Comment by OLgaByR** [comment]
> @OLgaByR should I delete it now and commit again ?

sure, we dont need  duplicate

**Comment by MarinaMone** [comment]
@OLgaByR done

**Review by EkaterinaRomankova — APPROVED** [review]

**Pull request merged**
