### PR TITLE
AT_01.05.03 | Login by email tab UI > Verify the agent is able to see Email input field and it has text 'Email'

### PR DESCRIPTION
**Pull request by Rom-T**
https://trello.com/c/hdvyU9XN/196-at010503-login-by-email-tab-ui-verify-the-agent-is-able-to-see-email-input-field-and-has-text-email

### CODE REVIEW

**Review by OLgaByR — APPROVED** [review]

**Review by OLgaByR — COMMENTED** [review]
Roman, it looks good to me, the only thing i would change is AT name, as it is grammatically incorrect to "Verify the agent is able to see Email input field and it has text 'Email'" or "Verify Email input field is visible and has text 'Email'"

**Review by OLgaByR — COMMENTED** [review]
and line 24 -  i think should be right after loginPopup..?  =>  loginPopup.getEmailInput()

**Comment by Rom-T** [comment]
> and line 24 - i think should be right after loginPopup..? => loginPopup.getEmailInput()

I used to think it was the right way too. But after Masha said that if you want to transfer to the next line, then you need to transfer the first method as well.

**Comment by Rom-T** [comment]
> t 'Emai

I copied the title from the Check List. Thanks for noticing. Fixed everywhere (Check List, Trello, VSC)

**Pull request merged**
